### ISSUE TITLE
desktop::virtualbox-guest recipe hideen dependency on DM

### ISSUE THREAD

**Issue by jamesconant** [http-418/chef-desktop#17]
When running the the `desktop::graphics` recipe, it pulls in the `desktop::virtualbox-guest` recipe [here](https://github.com/http-418/chef-desktop/blob/master/recipes/graphics.rb#L41-L44).

That's all well and good (I guess?). What happens, however, is that vb-guest assumes that the KDE recipe has been included and run. In my case, I don't use KDE (and thus don't have kdm installed), but there is no check around the service restart command found [here](https://github.com/http-418/chef-desktop/blob/master/recipes/virtualbox-guest.rb#L42).

To be honest, I don't know what the correct or desired "fix" here is. Obviously I can create my own recipe which doesn't include the restart, but I'm not sure what the implication of that would be. Fwiw, I'm using i3 wm (but I think you already knew that).

**Comment by http-418** [comment]
It's not forced to be kdm.

The specific kind of display manager could be discovered at converge time and restarted via lazy evaluation or something but that's a lot more complicated.  It was easier to just hardcode it into a variable since there are only half a dozen common options.

You can override the value anywhere you want, or fix the code once and for all with a smarter restart.  

Overriding the value will be a lot easier.
